name: flutter_news_app
description: A simple Flutter news app that fetches articles from the NewsAPI.

publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4  # Added the http dependency
  cupertino_icons: ^1.0.2  # Cupertino icons for iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Lints for better coding practices

flutter:
  uses-material-design: true
